FILESEXTRAPATHS:prepend := "${THISDIR}/${PN}:"

COMPATIBLE_MACHINE:nanopc-t6 = "nanopc-t6"

SRC_URI:append:nanopc-t6 = " file://0002-update-device-tree-for-NAVONZ-Board.patch"
SRC_URI:append:nanopc-t6 = " file://0003-fix-gmac1.patch"
SRC_URI:append:nanopc-t6 = " file://0004-gmac-phy-add-reset-pin.patch"
SRC_URI:append:nanopc-t6 = " file://0005-LED-correct-system-led-and-user-led.patch"
SRC_URI:append:nanopc-t6 = " file://0006-pcie30-disable-pcie3.0.patch"
SRC_URI:append:nanopc-t6 = " file://0007-enable-es8316-codec.patch"
SRC_URI:append:nanopc-t6 = " file://0008-test-deconfig.patch"
SRC_URI:append:nanopc-t6 = " file://0009-audio-sound-card-driver-changes.patch"
SRC_URI:append:nanopc-t6 = " file://0010-gmac1-phy.patch"
SRC_URI:append:nanopc-t6 = " file://0011-gmac1-reset-active-low.patch"
SRC_URI:append:nanopc-t6 = " file://0012-enable-sata2.patch"
SRC_URI:append:nanopc-t6 = " file://0013-sata2-fix-error.patch"
SRC_URI:append:nanopc-t6 = " file://0001-enable-uart-7.patch"
SRC_URI:append:nanopc-t6 = " file://0001-update-device-tree-based-on-latest-schematic.patch"
SRC_URI:append:nanopc-t6 = " file://0001-dts-correct-pci2.0-pwr_en-and-reset-for-external-wif.patch"
SRC_URI:append:nanopc-t6 = " file://0001-pcie2.0-2-correct-reset-level.patch"
SRC_URI:append:nanopc-t6 = " file://0001-update-dts-enable-usb-phy-2-and-disable-ir.patch"
SRC_URI:append:nanopc-t6 = " file://0001-test-intel-wifi.patch"
SRC_URI:append:nanopc-t6 = " file://0001-enable-pci-wifi.patch"
SRC_URI:append:nanopc-t6 = " file://0001-dts-control-maiana-hat-module.patch"
SRC_URI:append:nanopc-t6 = " file://0001-dts-test-typec-dp.patch"